### ISSUE TITLE
Structure completion doesn't complete functions or procedures marked as pervasive or body

### ISSUE THREAD

**Issue by ghost** [Open-Turing-Project/OpenTuring#15]
^that.

**Comment by trishume** [comment]
Fixed in development release.

**Comment by ghost** [comment]
50% fixed. Pervasive and \* don't work yet. Also recommended improvement: make it so that "forward proc i" completes to "forward proc i ; body proc i; ; end i" where ; is a newline.

**Comment by trishume** [comment]
fixed. last bit would require major overhaul of the completion system.
