### ISSUE TITLE
drawpic function broken.

### ISSUE THREAD

**Issue by ghost** [Open-Turing-Project/OpenTuring#18]
It doesn't work. The examples from the documentation don't even work.

**Comment by trishume** [comment]
Pic.Draw or drawpic?

**Comment by ghost** [comment]
drawpic

**Comment by trishume** [comment]
This one seems to be called by weird pointer finagling in mdiopic.c

Problem is when bad memory is passed to mdiopic.c line 583 by line 797

**Comment by trishume** [comment]
Fixed. Tom West seems to love pointer casts. Unfortunately they one of C's most evil features.
