### ISSUE TITLE
Change syntax highlighting colors

### ISSUE THREAD

**Issue by ghost** [Open-Turing-Project/OpenTuring#19]
The world would be so much nicer if the syntax highlighter's colors were reversed or changed. Keywords should be blue and identifiers should be black. library functions should be teal. Maybe read colors from the settings file.

**Comment by trishume** [comment]
This will be changed in the new editor.

**Comment by tonytargonski** [comment]
Or you know, let one define themes of their own instead of following the preference of one particular user, as many editors do

http://manual.macromates.com/en/themes
http://sublimetext.info/docs/en/extensibility/syntaxdefs.html
http://vimdoc.sourceforge.net/htmldoc/syntax.html

**Comment by trishume** [comment]
Currently I have a light theme and a dark theme. But I will probably add support for gedit themes as they are very simple.
