### ISSUE TITLE
Status bar doesn't update when you save via keyboard shortcut

### ISSUE THREAD

**Issue by ghost** [Open-Turing-Project/OpenTuring#21]
... whereas it shows "[...] Saved - ### lines - ### bytes" if you save via the tool bar.

**Comment by trishume** [comment]
It shows it for me.

**Comment by ghost** [comment]
Heyheyhey don't just close it just cuz it works for you...

**Comment by trishume** [comment]
I have code that proves that it works and it works on my computer. Demonstrate it not working on a school computer in front of me and I will believe it.

**Comment by ghost** [comment]
k
