### ISSUE TITLE
The Time.Date Function Causes a Crash.

### ISSUE THREAD

**Issue by trishume** [Open-Turing-Project/OpenTuring#28]
When called, the Time.Date function crashes the editor. It is possible that other time functions crash the editor as well.

This is untested. Submitted by Raknarg.

This is important. Crashing is bad.

**Comment by ghost** [comment]
Yup. He's right.

**Comment by ghost** [comment]
Also I forgot to save my project before testing this bug so I lost a bunch of code.

**Comment by trishume** [comment]
Ctrl+S after every line. But otherwise do other Time.X functions work? Time.Elapsed, Time.Sec, etc...

**Comment by ghost** [comment]
Seems Time functions that deal with converting Seconds-since-Unix-Epoch to and from other formats are broken. Time.SecDate causes an error, Time.SecParts causes the program to hang, and Time.SecStr causes an error as well.

**Comment by ghost** [comment]
Also the "time" function causes a crash as well.

**Comment by trishume** [comment]
Fixed in dev branch. At some point time_t became 64 bit and not 32 bit. This caused int pointers to be cast to long pointers causing an extra byte to be read after the int.
