### ISSUE TITLE
Master Build fails using visual studio 2010

### ISSUE THREAD

**Issue by rlalance** [Open-Turing-Project/OpenTuring#32]
The current build fails due to a problem with HTMLHELP.LIB

2 of the 16 projects fails building.

15>------ Rebuild All started: Project: Prolog, Configuration: Debug Win32 ------
15>Build started 22/12/2012 4:43:30 PM.
15>_PrepareForClean:
15>  Deleting file "Debug\Prolog.lastbuildstate".
15>InitializeBuildStatus:
15>  Creating "Debug\Prolog.unsuccessfulbuild" because "AlwaysCreate" was specified.
15>LINK : fatal error LNK1181: cannot open input file '....\Debug\HTMLHELP.LIB'
15>
15>Build FAILED.

16>------ Rebuild All started: Project: Turing, Configuration: Debug Win32 ------
16>Build started 22/12/2012 4:43:35 PM.
16>_PrepareForClean:
16>  Deleting file "...\Debug\Turing.lastbuildstate".
16>InitializeBuildStatus:
16>  Touching "...\Debug\Turing.unsuccessfulbuild".
16>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(108,5): warning MSB5018: Failed to delete the temporary file "C:\Users\toc\AppData\Local\Temp\7c263d9f43c94f63825d30e18d57d5b8.exec.cmd". Access to the path 'C:\Users\toc\AppData\Local\Temp\7c263d9f43c94f63825d30e18d57d5b8.exec.cmd' is denied.
16>LINK : fatal error LNK1181: cannot open input file '..\Debug\HTMLHELP.LIB'
16>
16>Build FAILED.

**Comment by ghost** [comment]
Hey Tristan I _told you_ people would have trouble with this.
Richard, you need to link htmlhelp.lib which you can download here: https://www.dropbox.com/s/bo4t7ancispmm9l/htmlhelp.lib

**Comment by rlalance** [comment]
Searched the project and found the file somewhere in the folder hierarchy.
Might not be a bad idea to fix the project so I compiles and links right away.
I can now compile turing.exe.

Thanks.
