### ISSUE TITLE
Turing editor to remember the last folder a file was opened

### ISSUE THREAD

**Issue by rlalance** [Open-Turing-Project/OpenTuring#36]
It would be nice to have the editor to remember where was the last file opened, so when we re-opened the editor, we do not have to navigate back to our source code folder.

**Comment by ghost** [comment]
This exists. Check the preferences window.

**Comment by rlalance** [comment]
Sorry, can't find that option in the preferences.

**Comment by ghost** [comment]
"Start in Last Active Directory"?

**Comment by rlalance** [comment]
Correct. File open will start in the folder the last file was opened.
