### ISSUE TITLE
project missing a license file

### ISSUE THREAD

**Issue by tonytargonski** [Open-Turing-Project/OpenTuring#8]
This would probably have to be interpreted from the conditions under which you've obtained the initial source base. Assuming that you can do anything, MIT license is nice (very permissive) (WTFPL is kind of hilarious). Though software licensing is a complicated subject, so I'd invite some discussion on the topic.

**Comment by trishume** [comment]
I was thinking WTFPL. But MIT might be better. I'll get a liscensce file

**Comment by trishume** [comment]
Added an MIT license file.
